# Generated by Django 3.2.9 on 2021-12-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='active',
            new_name='done',
        ),
    ]
